name: star_printer_example
description: Demonstrates how to use the star_printer plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  star_printer:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/images/
